id: P38359811
initial_creation_type: ocr
source_metadata:
  volumes:
    b0793fd3d0a64b469b20383af12e0e2e:
      base_file: v097.txt
      image_group_id: I1PD95942
      title: ''
      total_pages: 1198
      volume_number: 97
