id: DA9211AEB
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-03-08T06:43:05+00:00'
last_modified: '2022-05-30T04:30:36.050028+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    577e:
      image_group_id: I1PD95942
      title: ཚད་མ་ཀུན་ལས་བཏུས་པའི་འགྲེལ་པ།
      total_pages: 1198
      order: 97
      base_file: 577e.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
